### ISSUE TITLE
Checklist: ERPNext in Hindi Course Outline

### ISSUE THREAD

**Issue by wisharya** [wisharya/ERPNext-in-Hindi#1]
### 1. Introduction to ERP

- [ ] What is ERP?

- [ ] What is ERPNext?

### 2. Introduction Free and Open Source (FOSS)

- [ ] What is Proprietary Software?

- [ ]  What is FOSS

### 3. Getting Started with ERPNext
 - [ ] The Monolith
 - [ ] Overview of Modules
 - [ ] Concepts and Terms

### 4. Basic Setup
 - [ ] Company Setup
 - [ ] Global Default
 - [ ] System Setting

### 5. Data Import
 - [ ] Data Import
 - [ ] Data Export
 - [ ] Download Data Backup

### 6. User and Permissions
 - [ ] Users and Permissions
 - [ ] Adding Users
 - [ ] User Permissions

### 7. Doctype
 - [ ] What is doctype
 - [ ] What is field

### 8. Intro to Website Module
 - [ ] Web Page
 - [ ] Web Template
 - [ ] Website Setting
 - [ ] Blog
 - [ ] Web form
 - [ ] Website Theme
